### ISSUE TITLE
Wrong URL with Google Maps JavaScript API's extensionless URL

### ISSUE THREAD

**Issue by mfidemraizer** [HeinrichFilter/systemjs-plugin-googlemaps#3]
I've found the following issue. 

When I provide Google Maps JavaScript API's URL in the `system.config` where the whole script file URL has no extension, SystemJS adds the extension to the first query string value. For example:
- `//maps.googleapis.com/maps/api/js?v=3` is turned into `//maps.googleapis.com/maps/api/js?v=3.js`.

In my case, this issue gives a wrong API version `v=3.js`.

I'm going to provide a pull request in some minutes to fix this issue...

**Comment by HeinrichFilter** [comment]
Thanks @mfidemraizer 

My current hack is to add an `&` to the end of the URL. That way the appended `.js` is ignored. (see the example in the README)

But it would be nice if you can submit a PR with a cleaner approach.

**Comment by mfidemraizer** [comment]
Well the approach is very stupid... :sweat_smile: It's just removing the `.js` extension from the `src` variable.

I believe that it should work well, because this plugin is designed to exclusively load this Google JavaScript and, for now, its path has no extension. I don't see side-effects because of hard-coding the extension removal... 

What's your opinion?

**Comment by HeinrichFilter** [comment]
To be honest, it still feels like a bit of a hack.

I'm not sure what the correct way would be, though? It would be ideal if you could configure SystemJS not to add the `.js`.

If we go down the replace route then we should only remove the `.js` if it is right at the end of the string.

**Comment by mfidemraizer** [comment]
@HeinrichFilter It can be still a fix while we find a better solution. 

My problem is if we don't include this "stupid fix" I can't use your module at all... (well, I could add the ampersand you said above but...)

**Comment by mfidemraizer** [comment]
@HeinrichFilter  Sorry, now I checked again your comment...

> If we go down the replace route then we should only remove the .js if it is right at the end of the string.

Where you expect to appear `.js` if it's not before the query string? Are you thinking about an URL like this? `http://whatever.com/file.js/blah.js?`. It would be very strange :smiley:

**Comment by HeinrichFilter** [comment]
Since this code is still a hack, it should be very specific and limit possible side-effects. 

Imagine Google ever makes the following alternative URL available:
`//maps.googleapis.com/maps.js?v=3`

Then it will be very confusing for the user if our code doesn't work with that URL.

You might argue that Google is unlikely to change/add URLs for their maps. However, someone else could copy this code for their plugin. You would not expect the plugin to change `http://whatever.com/file.js/blah.js?` into `http://whatever.com/file/blah?`

Wouldn't that be even stranger? :)

**Comment by mfidemraizer** [comment]
@HeinrichFilter 

Well, IMHO hypothetical side-effects shouldn't be covered in code. If some day Google changes their URI scheme, that day you/we can improve the code to support the new use case. 

> However, someone else could copy this code for their plugin. You would not expect the plugin to change http://whatever.com/file.js/blah.js? into http://whatever.com/file/blah?

Uhmmm... But that developer copy-pasting the code will need to decide if he/she's a copy-paste programmer or if he/she's integrating your code. It's not your fault that others would blindly integrate your code in other projects...

**Comment by HeinrichFilter** [comment]
Seems like we disagree (which is fine :smile: )

I believe it is the developer's responsibility to minimize the negative effects that a hack can have in the future.

If we change the line to `s.replace(/\.js$/, "")` then I'll be happy to include it. In my opinion, that adds enough practical value to the current plugin without introducing too much risk.

Do you want to update your PR or should I make the change?

**Comment by mfidemraizer** [comment]
If you give me a day I can update the PR ;P

**Comment by mfidemraizer** [comment]
> I believe it is the developer's responsibility to minimize the negative effects that a hack can have in the future.

I'm agree with your point. But I try to be realistic. My experience is that when you start to think "what if? what if?", you're trying to fix things that may never happen at all, and if some day happens, since I practice the **refactor or die** habit, once the issue has been raised, it's just about refactoring the code to support it. :smiley:

**Comment by vanthome** [comment]
Hi, I just wanted to add that I stumbled across the same issue. I think you should make it work just with a URL like this:

```
  "paths": {
    // putting this in "map" breaks SystemJS builder
    // Note: the trailing ampersand is needed so that the appended ".js" is ignored
    "google-maps": "https://maps.googleapis.com/maps/api/js"
  },
```

as this is the base URL most people use (without API key, without special libs).

Also, **please correct** the comment `// Note: the trailing ampersand is needed so that the appended ".js" is ignored` which I think is redundant by now.

**Comment by HeinrichFilter** [comment]
Added modified version of @mfidemraizer's fix and updated documentation according to @vanthome's suggestions.
